name: Publicar Portal REVIMO
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Obter ficheiros
        uses: actions/checkout@v5
      - name: Configurar e activar GitHub Pages
        uses: actions/configure-pages@v6
        with:
          enablement: true
      - name: Preparar site
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Publicar
        id: deployment
        uses: actions/deploy-pages@v4
